import fetch from 'node-fetch';

async function testContacts() {
  const baseUrl = 'http://localhost:3001/api';
  // Use the token from a previously registered user (e.g., from previous tests)
  // For simplicity here, I will rely on the token generated by test_auth.js if I run it together,
  // but since this is a separate test, I will assume a valid token for now for testing API structure.
  const token = 'YOUR_VALID_TOKEN_HERE'; 

  console.log('--- Testing Fetch Contacts ---');
  const res = await fetch(`${baseUrl}/users?search=Test`, {
    method: 'GET',
    headers: { 
        'Authorization': `Bearer ${token}`
    }
  });
  const data = await res.json();
  console.log('Contacts Response:', data);
}

testContacts().catch(console.error);
